### ISSUE TITLE
missing license field in package.json

### ISSUE THREAD

**Issue by DanielRuf** [streamich/react-universal-interface#21]
Currently https://github.com/streamich/react-universal-interface/blob/master/package.json has no license field.

This produces the following output when we run [licensee](https://www.npmjs.com/package/licensee) with `corrections: true`:

```yaml
react-universal-interface@0.6.2
  NOT APPROVED
  Terms: Invalid license metadata
  Repository: https://github.com/streamich/react-universal-interface.git
  Homepage: None listed
  Author: None listed
  Contributors: None listed
```
